from setuptools import setup

__version__ = "1.35.0"

setup(
    name="ritual-pipeline",
    version=__version__,
    url="https://github.com/ritual-app/utils/tree/main/logger",
    author="Ritual",
    py_modules=[
        "log_handlers",
        "init_opentelemetry",
        "single_instance_metaclass",
        "cloud_env",
        "app_config",
        "pipeline_utils",
        "fastapi_config",
        "dlq_endpoints",
        "health_endpoints",
        "global_config",
        "gcp_files",
        "file_helper",
        "error_handling",
        "prompt_endpoints",
        "pubsub_utils",
        "llm_utils",
        "const",
        "data_structure",
        "log_helper",
        "management_client",
        "retry_policy",
        "pubsub_opentelemetry.pubsub_instrumentation_provider",
        "pubsub_opentelemetry.subscriber_decorator",
        "pubsub_opentelemetry.version",
        "pubsub_opentelemetry.publisher_decorator",
        "pubsub_opentelemetry.utils",
        "temporal_utils.heartbeat",
        "temporal_utils.base_workflow",
        "temporal_utils.base_activity",
        "temporal_utils.config",
        "temporal_utils.worker",
        "temporal_utils.common",
        "temporal_utils.context_propagator",
    ],
)
